version: '3'
services:

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: p2p_exchange_nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            #DEV
            #- ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
            #PROD
            - ./docker/nginx/conf.d/appProd.conf:/etc/nginx/conf.d/app.conf 
            - ./docker/nginx/ssl:/etc/ssl
        links:
            - app


    #PHP Service
    app:
        env_file: .env
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        user: root
        image: php:8.2-fpm
        container_name: p2p_exchange_php
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/backend/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        links:
            - db

    #MySQL Service
    db:
        image: mysql:8
        container_name: p2p_exchange_mysql
        restart: always
        tty: true
        ports:
            - "33061:3306"
        environment:
            MYSQL_ROOT_PASSWORD: p2pExchange
            MYSQL_DATABASE: p2pExchange
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

    # NodeJS Service
    node:
        build:
            context: .
            dockerfile: ./docker/nodejs/Dockerfile
        container_name: p2p_exchange_node
        restart: unless-stopped
        tty: true
        ports:
            - "5173:5173"
        working_dir: /var/www
        volumes:
            - .:/var/www 

#Volumes
volumes:
    dbdata:
        driver: local
